### ISSUE TITLE
How to convert fixed byte array to string in IDBlockRaw structure and vice versa

### ISSUE THREAD

**Issue by dhruv050992** [sneusse/MdfTools#2]
How to convert fixed byte array ( public fixed byte IdFile[8]) to string and vice versa?

**Comment by sneusse** [comment]
SO is a nice resource for general questions like this:
https://stackoverflow.com/questions/11654562/how-to-convert-byte-array-to-string

```
var str = System.Text.Encoding.Default.GetString(array);
```

**Comment by dhruv050992** [comment]
Hi,

I have researched everything on SO.
I know if you have simple byte[], you can use, Encoding.GetString().

Here, I am asking about byte*, "It is showing me an error that, cannot use fixed size buffer in unfixed expression."

Can you please try it from your end and let me know the solution.

![image](https://user-images.githubusercontent.com/29755083/123234306-767fd880-d4f8-11eb-933f-ce8d794b7b20.png)

**Comment by sneusse** [comment]
Add this to the IdBlockRaw struct, for example.
```
        public string IdFileStr
        {
            get
            {
                fixed (byte* p = IdFile)
                {
                    return new string((sbyte*)p,0,8);
                }
            }
        }
```

**Comment by dhruv050992** [comment]
Thank you so much. It will help.
